export interface Dance {
  name: string;
  dancers: string[];
  song: string;
  artist: string;
}

export const dances: Dance[] = [
  // {
  //   name: 'Acro Jr A',
  //   dancers: [
  //     'Beugelink, Heartleigh',
  //     'Bukowski, Maylee',
  //     'Coates, Amelia',
  //     'Constable, Brynn',
  //     'Gowlovech, Capri',
  //     'Guillory, Maryn',
  //     'Hawley, Ellie',
  //     'Higginbotham, Payson',
  //     'Ritzko, Bailee',
  //   ],
  // },
  // {
  //   name: 'Acro Jr B',
  //   dancers: [
  //     'Brogdon, Hayden',
  //     'Brunk, Emily',
  //     'Burnham, Julie',
  //     'Dulaney, Penelope',
  //     'Haro, Amelia',
  //     'Hayslett, Grace',
  //     'Hester, Jillian',
  //     'Hester, Josslyn',
  //     'Neier, Lacey',
  //     'Song, Evelyn',
  //   ],
  // },
  {
    name: 'Acro Jr',
    song: 'We Are One',
    artist: 'Pitbull',
    dancers: [
      'Beugelink, Heartleigh',
      'Brogdon, Hayden',
      'Brunk, Emily',
      'Bukowski, Maylee',
      'Burnham, Julie',
      'Coates, Amelia',
      'Constable, Brynn',
      'Dulaney, Penelope',
      'Gowlovech, Capri',
      'Guillory, Maryn',
      'Haro, Amelia',
      'Hawley, Ellie',
      'Hayslett, Grace',
      'Hester, Jillian',
      'Hester, Josslyn',
      'Higginbotham, Payson',
      'Neier, Lacey',
      'Ritzko, Bailee',
      'Song, Evelyn',
    ],
  },
  {
    name: 'Acro I',
    song: 'The Passenger',
    artist: 'Lumix',
    dancers: [
      'Abuhmaidan, Isla',
      'Akert, Alaina',
      'Anderson, Sophia',
      'Boone, Juliette',
      'Carmona, Sofia',
      'Foley, Abigail',
      'Good, Elisabeth',
      'Hunter, Carson',
      'Olson, Desiree',
      'Song, Irene',
      'Toma, Rebekah',
    ],
  },
  {
    name: 'Acro II',
    song: 'Where Are You Now',
    artist: 'Calum Scott',
    dancers: [
      'Akert, Madi',
      'Albert, Lucy',
      'Boone, Clara',
      'Haro, Angelina',
      'Higginbotham, Ahnalee',
      'Marshall, Bailey',
      'Poku, Rebekah',
      'Sutton, Harper',
    ],
  },
  {
    name: 'Ballet I',
    song: 'A Dream Is a Wish Your Heart Makes',
    artist: 'Lily James',
    dancers: [
      'Armstrong, Natalie',
      'Addler, Harper',
      'Bichsel, Addilyn',
      'Bonnell, Daisy',
      'Brown, Rylie',
      'Damron, Devon',
      'Haro, Amelia',
      'Murphy, Joelle',
      'Nicely, Zari',
      'Vetter, Alexandra',
      'Vilorio, Emma',
      'Wolter, Ava',
      'Young, Joanna',
    ],
  },
  // {
  //   name: 'Ballet Techniques A',
  //   dancers: [
  //     'Balzarini, Brooke',
  //     'Kambham, Arianna',
  //     'Lenhart, Olivia',
  //     'Wolter, Ava',
  //     'Wells, Emma',
  //   ],
  // },
  // {
  //   name: 'Ballet Techniques B',
  //   dancers: [
  //     'Boone, Clara',
  //     'Hunter, Lainey',
  //     'Hunter, Maia',
  //     'Marshall, Bailey',
  //     'Rawlings, Vivian',
  //   ],
  // },
  {
    name: 'Ballet/Tap I Combo Wed 2:30pm (Ballet)',
    song: 'Bloom',
    artist: 'The Paper Kites',
    dancers: [
      'Arena, Eloise',
      'Coffee, Ellie',
      'Cosman, Charlotte',
      'Kinch, Hollyn',
      'Krznarich, Ava',
      'Ortiz, Gabriela',
      'Reeves, Makenna',
      'Ruedas, Selah',
      'Valentine, Grace',
      'Winney, Eleonora',
    ],
  },
  {
    name: 'Ballet/Tap I Combo Wed 2:30pm (Tap)',
    song: 'I Like You for You',
    artist: 'Animal Island',
    dancers: [
      'Arena, Eloise',
      'Coffee, Ellie',
      'Cosman, Charlotte',
      'Kinch, Hollyn',
      'Krznarich, Ava',
      'Ortiz, Gabriela',
      'Reeves, Makenna',
      'Ruedas, Selah',
      'Valentine, Grace',
      'Winney, Eleonora',
    ],
  },
  {
    name: 'Ballet/Tap I Combo Wed 4:15pm (Ballet)',
    song: 'Cover Me in Sunshine',
    artist: 'P!nk',
    dancers: [
      'Armenta, Jane',
      'Carlisle, Liana',
      'Eklund, Rylee',
      'Mann, Eleanor',
      'Mather, Kate',
      'O’Connor, Madeline',
      'Page, Annie',
      'Puckett, Madison',
      'Riewold, Henley',
      'Rosinbum, Lilli',
      'Sando, Gianna',
      'Schon, Riley',
      'Schroff, Madison',
      'Shkarayeva, Kira',
      'Stonham, Alice',
    ],
  },
  {
    name: 'Ballet/Tap I Combo Wed 4:15pm (Tap)',
    song: 'Sh-Boom',
    artist: 'The Chords',
    dancers: [
      'Armenta, Jane',
      'Carlisle, Liana',
      'Eklund, Rylee',
      'Mann, Eleanor',
      'Mather, Kate',
      'O’Connor, Madeline',
      'Page, Annie',
      'Puckett, Madison',
      'Riewold, Henley',
      'Rosinbum, Lilli',
      'Sando, Gianna',
      'Schon, Riley',
      'Schroff, Madison',
      'Shkarayeva, Kira',
      'Stonham, Alice',
    ],
  },
  {
    name: 'Ballet: Beginning Adult',
    song: 'TBD',
    artist: 'TBD',
    dancers: [
      'Callanan-Attebery, Christina',
      'Ellis, Dawn',
      'Ernster, Rachelle',
      'Hunter, Kristi',
      'Patterson, Suzi',
      'Sorenson, Becky',
      'Widney, Shannon',
      'Wo, Kathleen',
    ],
  },
  {
    name: 'Contemporary I',
    song: 'To Build a Home',
    artist: 'Cinematic Orchestra',
    dancers: [
      'Abney, Hanna',
      'Bala, Elizabeth',
      'Franco, Gia',
      'Hayslett, Grace',
      'Hester, Jillian',
      'Hester, Josslyn',
      'Neypes, Grace',
      'Walters, Alanna',
    ],
  },
  {
    name: 'Contemporary II',
    song: 'Constellations',
    artist: 'Ellie Holcomb',
    dancers: [
      'Carnahan, Emmanuelle',
      'Dollman, Coraline',
      'Hoelzen, Emma',
      'Hoelzen, Kate',
      'Ritter, Emily',
      'Yee, Hannah',
      'Wells, Emma',
    ],
  },
  {
    name: 'Hip Hop I',
    song: 'Move Your Feet',
    artist: 'Junior Senior',
    dancers: [
      'Akert, Alaina',
      'Balzarini, Brooke',
      'Boone, Juliette',
      'Campbell, Deborah',
      'Clarke, Christina',
      'Clarke, Douglas',
      'Flandrau, Mackenzie',
      'Flandrau, Olivia',
      'Foley, Abigail',
      'Marr, Olivia',
      'Murphy, Brynlie',
      'Parks, Pearl',
      'Santina, Camryn',
      'Sorenson, Leila',
      'Vaughn, Hailey',
    ],
  },
  {
    name: 'Hip Hop II',
    song: 'The Saints',
    artist: 'Andy Minio',
    dancers: [
      'Boone, Asher',
      'Dabas, Arnav',
      'Dalton, Alice',
      'De Anda, Sofia',
      'Gerald, Sophie',
      'Ghiurau, Ella',
      'Ghiurau, Lia',
      'Londonson, Elise',
      'Ramirez, Gabriella',
      'Stevens, Reagan',
    ],
  },
  {
    name: 'Jazz I',
    song: 'It Only Gets Better',
    artist: 'WILD',
    dancers: [
      'Boyd, Gracee',
      'Bukowski, Maylee',
      'Delatorre, Charlotte',
      'Dillon, Paisley',
      'Focht, Delaney',
      'Ghiurau, Jade',
      'Little, Payson',
      'Rypkema, Chloe',
      'Sari Terzi, Valeria',
      'Shearer, Sofia',
      'Toma, Emma',
      'Widney, Emery',
    ],
  },
  {
    name: 'Jazz II',
    song: 'Dancing My Way',
    artist: 'Wyn Starks',
    dancers: [
      'Block, Tessa',
      'Carmona, Selah',
      'Emery, Paisley',
      'Lenhart, Olivia',
      'Sutton, Harper',
    ],
  },
  {
    name: 'Modern/Lyrical',
    song: 'Grow',
    artist: 'Frances',
    dancers: [
      'Boone, Clara',
      'Capelle, Madeline',
      'Coloma Emilie',
      'Duncan, Isla',
      'Higginbotham, Ahnalee',
      'Highfill, Emma',
      'Lenhart, Olivia',
      'Marshall, Bailey',
      'Massaro, Maddie',
      'Poku, Maleah',
      'Sorenson, Leila',
    ],
  },
  {
    name: 'Musical Theater I',
    song: 'Put On a Happy Face',
    artist: 'Dick Van Dyke',
    dancers: [
      'Beliveau, Kenna',
      'Benavides, Elishka',
      'Kambham, Arianna',
      'Kimble, Emmelyn',
      'Larish, Eva',
      'Perez, Lillian',
      'Stewart, Mariah',
      'Sullins, Alyssa',
      'Taing, Riley',
      'Walters, Alanna',
    ],
  },
  {
    name: 'Musical Theater III',
    song: 'Super Trouper',
    artist: 'ABBA',
    dancers: [
      'Boone, Clara',
      'Hunter, Lainey',
      'Hunter, Maia',
      'Marshall, Bailey',
      'Rawlings, Vivian',
    ],
  },
  {
    name: 'Musical Theater II',
    song: '9 To 5',
    artist: '',
    dancers: [
      'Bervig, Ava',
      'Bervig, Olivia',
      'Campbell, Deborah',
      'Dorman, Grace',
      'Iverson, Tanya',
      'Marr, Olivia',
      "O'Connor, Caitlyn",
      'Overson, Brielle',
      'Rawlings, Eden',
      'Wells, Mikaela',
    ],
  },
  {
    name: 'Pre-Ballet & Pre-Tap Wed AM',
    song: 'Build Me Up Buttercup',
    artist: 'The Foundations',
    dancers: [
      'Armstrong, Crystal',
      'Arnold, Emma',
      'Arnold, Rebecca',
      'Bervig, Cora',
      'Campbell, Tatum',
      'Drown, Marlowe',
      'Hansen, Jovie',
      'Johnson, McKenzie',
      'Kohutiar, Luisa',
      'Malito, Rayah',
      'Mather, Sadie',
      'Stapley, Aurora',
    ],
  },
  {
    name: 'Pre-Ballet & Pre-Tap Wed 11',
    song: '',
    artist: '',
    dancers: [
      'Harrier, Alice',
      'Laun, Claire',
      'Lonca, Abigail',
      'Mortensen, Lucy',
      'Ratkovich, Amelia',
      'Segura, Isa',
      'Sethi, Saisha',
      'Stan, Ella',
      'Tunney, Brynn',
    ],
  },
  {
    name: 'Pre-Ballet & Pre-Tap Thurs AM',
    song: 'The Puppy Song',
    artist: 'Harry Nilsson',
    dancers: [
      'Buckenberger, Lyncoln',
      'Cunningham, Genesis',
      'Douglass, Maci',
      'Dunn, Harper',
      'Fetters, Rosabeth',
      'Howerton, Lennon',
      'Lind, Everly',
      'Lizama, Skylar',
      'Nielsen, Penny',
      'Page, Sadie',
      'Prenovost, Piper',
      'Ratiu, Hailey',
      'Riewold, Hayden',
      'Stefani, Nicoletta',
      'Taylor, Leelah',
      'Wackett, Emilia',
    ],
  },
  {
    name: 'Pre-Ballet & Pre-Tap Thurs PM',
    song: 'Up With End Credits',
    artist: 'Michael Giacchino',
    dancers: [
      'Aja, Sophie',
      'Baldwin, Kinsley',
      'Brown, Maya',
      'Burnham, Amy',
      'Conner, Juliana',
      'Cunningham, Ariella',
      'Gaines, Anniston',
      'Jacobo, Taylor',
      'Jorbin, Amelia',
      'Kirara, Makena',
      'Marshall, Audrey',
      'Moncrieff, Charley',
      'Musarra, Alessia',
      'Reaney, Charlotte',
      'Rivera, Isla',
      'Tacheny, Gemma',
      'Thomas, Isla',
      'Vetter, Addison (Addie)',
    ],
  },
  {
    name: 'Sweetheart',
    song: "Those Boots (Deddy's Song)",
    artist: 'Lainey Wilson',
    dancers: [
      'Aja, Sophie',
      'Armstrong, Crystal',
      'Arnold, Emma',
      'Arnold, Rebecca',
      'Baldwin, Kinsley',
      'Bervig, Cora',
      'Brown, Maya',
      'Buckenberger, Lyncoln',
      'Burnham, Amy',
      'Campbell, Tatum',
      'Conner, Juliana',
      'Cunningham, Ariella',
      'Cunningham, Genesis',
      'Douglass, Maci',
      'Drown, Marlowe',
      'Dunn, Harper',
      'Fetters, Rosabeth',
      'Gaines, Anniston',
      'Hansen, Jovie',
      'Harrier, Alice',
      'Howerton, Lennon',
      'Jacobo, Taylor',
      'Johnson, McKenzie',
      'Jorbin, Amelia',
      'Kirara, Makena',
      'Kohutiar, Luisa',
      'Laun, Claire',
      'Lind, Everly',
      'Lizama, Skylar',
      'Lonca, Abigail',
      'Malito, Rayah',
      'Marshall, Audrey',
      'Mather, Sadie',
      'Moncrieff, Charley',
      'Mortensen, Lucy',
      'Musarra, Alessia',
      'Nielsen, Penny',
      'Page, Sadie',
      'Prenovost, Piper',
      'Ratiu, Hailey',
      'Ratkovich, Amelia',
      'Reaney, Charlotte',
      'Riewold, Hayden',
      'Rivera, Isla',
      'Segura, Isa',
      'Sethi, Saisha',
      'Stan, Ella',
      'Stapley, Aurora',
      'Stefani, Nicoletta',
      'Tacheny, Gemma',
      'Taylor, Leelah',
      'Thomas, Isla',
      'Tunney, Brynn',
      'Vetter, Addison (Addie)',
      'Wackett, Emilia',
    ],
  },
  {
    name: 'Tap I',
    song: "I Won't Let You Down",
    artist: 'OK Go',
    dancers: [
      'Bervig, Isla',
      'Brown, Rylie',
      'Chandiramani, Anysia',
      'Chandiramani, Zyah',
      'Dorman, Caroline',
      'Rawlings, Grace',
      'Shkarayev, Ivan',
    ],
  },
  {
    name: 'Tap II',
    song: "If You're Gonna Play in Texas",
    artist: 'Alabama',
    dancers: [
      'Bervig, Ava',
      'Bervig, Olivia',
      'Dorman, Grace',
      'Hunter, Carson',
      'Iverson, Paisly',
      'Overson, Addy',
      'Rawlings, Eden',
      'Wells, Anneliese',
      'Wells, Jonah',
    ],
  },
  {
    name: 'Tap III',
    song: 'Irish Song (or other?)',
    artist: 'The Railers (or live?)',
    dancers: [
      'Boone, Asher',
      'Boone, Clara',
      'Carnahan, Emmanuelle',
      'Hunter, Lainey',
      'Hunter, Maia',
      'Palacios, Audrey',
      'Rawlings, Vivian',
    ],
  },
  {
    name: 'Tap: Adults',
    song: 'Bennie and the Jets (2018)',
    artist: 'Elton John/P!nk/Logic',
    dancers: [
      'Brown, Nicole',
      'Coloma, Rhea',
      'Duncan, Rhea',
      'Hale, Trista',
      'Katie Taylor',
      'Lin, Yvonne',
      'Moncrieff, Lynsey',
      'Patterson, Suzi',
      'Samson, Dora',
      'Snyder, Nancy',
    ],
  },
  {
    name: 'SpecTAPular',
    song: 'Echo Dance?',
    artist: 'Live?',
    dancers: [
      'Bervig, Ava',
      'Bervig, Isla',
      'Bervig, Olivia',
      'Boone, Asher',
      'Boone, Clara',
      'Brown, Nicole',
      'Brown, Rylie',
      'Carnahan, Emmanuelle',
      'Chandiramani, Anysia',
      'Chandiramani, Zyah',
      'Coloma, Rhea',
      'Dorman, Caroline',
      'Dorman, Grace',
      'Duncan, Rhea',
      'Hale, Trista',
      'Hunter, Carson',
      'Hunter, Lainey',
      'Hunter, Maia',
      'Iverson, Paisly',
      'Katie Taylor',
      'Lin, Yvonne',
      'Moncrieff, Lynsey',
      'Overson, Addy',
      'Palacios, Audrey',
      'Patterson, Suzi',
      'Rawlings, Eden',
      'Rawlings, Grace',
      'Rawlings, Vivian',
      'Samson, Dora',
      'Shkarayev, Ivan',
      'Snyder, Nancy',
      'Wells, Anneliese',
      'Wells, Jonah',
    ],
  },
];
